version: "0.2"
words:
  - aliasgroup
  - allowtransparency
  - APITOKEN
  - appname
  - appnamehere
  - Authentik
  - Authexample
  - authkey
  - autoconnect
  - AUTOSYNC
  - backupname
  - basicauthexample
  - bazarr
  - bugfixer's
  - bungeecord
  - chainname
  - cheatsheet
  - cloudflared
  - Cloudflareddns
  - collabora
  - configfile
  - configmap
  - containo
  - daemonset
  - dbcreds
  - dbengine
  - ddns
  - Djava
  - DNAT
  - dockerized
  - duplicati
  - dynmap
  - Entrypoints
  - eptgmk
  - Fireshare
  - fullname
  - gibibyte
  - gluster
  - GUNICORN
  - healthcheck
  - healthchecks
  - hostpath
  - hyperconverged
  - hyperthread
  - iban
  - ingressclasses
  - ingressroutes
  - ingressroutetcps
  - ingressrouteudps
  - integrationsenabled
  - ipaddr
  - ixcert
  - ixsystems
  - jackett
  - jacobalberty
  - jailman
  - javaprefs
  - killswitch
  - kjeld
  - kube
  - kubeconfig
  - kubectl
  - kubernetes
  - lancache
  - lebbing
  - letsencrypt
  - lidarr
  - loadbalancer
  - logfile
  - loolwsd
  - mailenabled
  - Mailgun
  - mariadbcreds
  - mediafiles
  - meshroom
  - metallb
  - middlewares
  - middlewaretcps
  - Mikrotik
  - milicpu
  - minecraft
  - minio
  - modelstore
  - modports
  - mountpoint
  - multihost
  - neko
  - netdata
  - nextcloud
  - nobind
  - nodeport
  - nodeports
  - notebookbar
  - ornias
  - ovpn
  - PASSWRD
  - pgid
  - photoprism
  - pihole
  - plainhost
  - plex
  - preconfigured
  - prefs
  - Preload
  - proto
  - puid
  - putregexhere
  - pvcname
  - pvcpath
  - quotum
  - radarr
  - raknet
  - ramdisk
  - rcon
  - rcontcp
  - RECORDTYPES
  - registeringats
  - reneg
  - replacementurlhere
  - resolv
  - sabnzbd
  - schouten
  - selfsigned
  - SERVERCONFIG
  - serverstransports
  - serviceexpert
  - smallblock
  - sonarr
  - sonarrsabnzbd
  - Sonatype
  - srcsets
  - ssvnc
  - statefulset
  - staticfiles
  - steamcommunica
  - steammasterser
  - subchart
  - sublist
  - subquestion
  - subquestions
  - svcname
  - syncthing
  - tailscale
  - targetport
  - tccr
  - teamspeak
  - testpassword
  - testuser
  - themenamehere
  - tlsoptions
  - tlsstores
  - traefik
  - traefikservices
  - truecharts
  - truenas
  - truetool
  - unet
  - unifi
  - userspace
  - valheim
  - vaultwarden
  - vdev
  - vm's
  - webbasecontrol
  - webpanel
  - websecure
  - weejewel
  - xsystems
  - zwavejs
