apiVersion: v2
appVersion: "0.11.1"
dependencies:
- name: common
  repository: https://library-charts.truecharts.org
  version: 9.2.8
deprecated: false
description: NVR With Realtime Object Detection for IP Cameras
home: https://github.com/truecharts/apps/tree/master/charts/incubator/frigate
icon: https://raw.githubusercontent.com/slackr31337/truenas-catalog/main/stable/frigate/frigate.png
keywords:
- encode
- nvr
- media
- frigate
kubeVersion: '>=1.16.0-0'
maintainers:
- email: info@truecharts.org
  name: TrueCharts
  url: https://truecharts.org
name: frigate
sources:
- https://github.com/blakeblackshear/frigate
- https://hub.docker.com/r/blakeblackshear/frigate
type: application
version: 0.11.1
annotations:
  truecharts.org/catagories: |
    - nvr
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
