image:
  repository: blakeblackshear/frigate
  pullPolicy: IfNotPresent
  tag: 0.11.0

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

env:
  FRIGATE_RTSP_PASSWORD: "secret"
  NVIDIA_DRIVER_CAPABILITIES: "all"
  NVIDIA_VISIBLE_DEVICES: "all"

persistence:
  cache:
    enabled: true
    mountPath: "/tmp/cache"
    type: "emptyDir"
  shm:
    enabled: true
    mountPath: "/dev/shm"
    type: "emptyDir"
    medium: "Memory"
  media:
    enabled: true
    type: "hostPath"
    mountPath: "/media/frigate"
  config-file:
    enabled: true
    type: "hostPath"
    mountPath: "/config/config.yml"

service:
  main:
    ports:
      main:
        targetPort: 5000
        port: 5000
  rtmp:
    enabled: true
    ports:
      rtmp:
        protocol: TCP
        enabled: true
        port: 1935
        targetPort: 1935

ingress:
  rtmp:
    autoLink: true

portal:
  enabled: true
