image:
  repository: ghcr.io/pterodactyl/panel
  pullPolicy: IfNotPresent
  tag: v1.10.1@sha256:c1bd630fd3832c179ca67b070a81a8fac0bdd1f9a63c314fcd4671e143debfc

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0
portal:
  enabled: true
service:
  main:
    ports:
      main:
        targetPort: 80
        port: 8080

ingress:
  
persistence:
  logs:
    enabled: true
    mountPath: "/app/storage/logs"
  nginx:
    enabled: true
    mountPath: "/etc/nginx/http.d"
  config:
    enabled: true
    mountPath: "/app/var"
