image:
  repository: ghcr.io/pterodactyl/panel
  pullPolicy: IfNotPresent
  tag: v1.10.1@sha256:c1bd630fd3832c179ca67b070a81a8fac0bdd1f9a63c314fcd4671e143debfc6

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0
  
#secretEnv:
#  DB_PASSWORD: "changeme"
#  REDIS_PASSWORD: "changeme"
  
env:
  APP_URL: "http://panel.example.com"
  APP_ENV: "production"
  APP_ENVIRONMENT_ONLY: "false"
  APP_TIMEZONE: "UTC"
  APP_SERVICE_AUTHOR: "slackr31337@gmail.com"
  TRUSTED_PROXIES: "*"
  CACHE_DRIVER: "redis"
  SESSION_DRIVER: "redis"
  QUEUE_DRIVER: "redis"
  REDIS_HOST: "redis.ix-redis.svc.cluster.local"
  DB_HOST: "mariadb.ix-mariadb.svc.cluster.local"
  DB_PORT: 3306
  DB_DATABASE: "panel"

persistence:
  app:
    enabled: true
    mountPath: "/app/var"
  nginx:
    enabled: true
    mountPath: "/etc/nginx/http.d"
  logs:
    enabled: true
    mountPath: "/app/storage/logs"

