image:
  repository: blakeblackshear/frigate
  pullPolicy: IfNotPresent
  tag: 0.10.1-amd64

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0
portal:
  enabled: true
service:
  main:
    ports:
      main:
        targetPort: 5000
        port: 5000
  rtmp:
    enabled: true
    ports:
      rtmp:
        protocol: TCP
        enabled: true
        port: 1935
        targetPort: 1935

ingress:
  rtmp:
    autoLink: true

frigate:
  mqtt:
    host: mosquitto.ix-mosquitto.svc.cluster.local
    port: 1883
    authentitcated: false
    username: mqtt_user
    password: password
  ffmpeg:
    #hwaccel_args: -hwaccel cuda
    input_args: -threads 2 -vsync 0 -avoid_negative_ts make_zero -fflags nobuffer+igndts+genpts+discardcorrupt -flags low_delay -stimeout 5000000 -reorder_queue_size 10000 -use_wallclock_as_timestamps 1 -rtsp_transport tcp
    output_args:
      record: -f segment -segment_time 10 -segment_format mp4 -reset_timestamps 1 -strftime 1 -c:v copy -c:a aac
  birdseye:
    enabled: true
    mode: motion
  live:
    quality: 6
  snapshots:
    enabled: True
    retain:
      default: 30
  cameras:
    - name: driveway
      mqtt:
        enabled: False
      objects:
        track:
          - person
          - car
          - motorcyle
          - cat
          - dog
      detect:
        height: 720
        width: 1280
      inputs:
        - path: rtsp://{FRIGATE_CAMERA1}:554/cam/realmonitor?channel=1&subtype=0
          roles:
            - record
        - path: rtsp://{FRIGATE_CAMERA1}:554/cam/realmonitor?channel=1&subtype=1
          roles:
            - detect
            - rtmp
      record:
        enabled: True
        retain:
           days: 0

      best_image_timeout: 60
      snapshots:
        enabled: True
persistence:
  cache:
    enabled: true
    mountPath: "/tmp/cache"
    type: "emptyDir"
  shm:
    enabled: true
    mountPath: "/dev/shm"
    type: "emptyDir"
    medium: "Memory"
  media:
    enabled: true
    mountPath: "/media/frigate"
