image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/pterodactyl/wings
  tag: v1.7.0

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

secretEnv:
  DB_PASSWORD: "secret"

env:
  TZ: "UTC"
  WINGS_USERNAME: "pterodactyl"
  WINGS_UID: 568
  WINGS_GID: 568

persistence:
  config:
    enabled: true
    mountPath: "/etc/pterodactyl/"
  data:
    enabled: true
    type: hostPath
    mountPath: "/var/lib/pterodactyl/"
    hostPath: "/var/lib/pterodactyl/"
  temp:
    enabled: true
    type: hostPath
    hostPath: "/tmp/pterodactyl/"
    mountPath: "/tmp/pterodactyl/"
  containers:
    enabled: true
    type: hostPath
    hostPath: "/mnt/pool01/ix-applications/docker/containers"
    mountPath: "/var/lib/docker/containers/"
  socket:
    enabled: true
    type: hostPath
    hostPath: "/run/docker.sock"
    mountPath: "/var/run/docker.sock"

service:
  main:
    ports:
      main:
        targetPort: 8080
        port: 8080
  ssh:
    enabled: true
    ports:
      ssh:
        enabled: true
        targetPort: 2022
        port: 2022

portal:
  enabled: true
